// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdysqxxpvbgjpupidybu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkeXNxeHhwdmJnanB1cGlkeWJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MjQ5MTIsImV4cCI6MjA2MzUwMDkxMn0.9wwMMwue6--rsoNhtqRvhdG69FGAZj-Jgy7ZOt5v_eE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);